<h1 align=right><font size = 2>Author: ivanjdevs</font></h1>

<h1 align=center><font size = 5>Scraping some data from football web pages</font></h1>

<p><font size=3> Primero importamos las librerías requeridas:</font></p>

In [ ]:
## pip install html5lib   # uncomment this line if you don't have this parser already installed

In [1]:
from bs4 import BeautifulSoup # this module helps in web scrapping.
import requests  # this module helps us to download a web page
import pandas as pd # tha famous scientific library to deal with dataframes
import html5lib  #  the parser we want to use to parse the HTML content

<p><font size = 3> Download the webpage at the url </font></p>

In [2]:
url = "https://fbref.com/es/comps/9/Estadisticas-de-Premier-League"

response = requests.get(url)
print(response.status_code)
#If we get status code=200, the connection is ok

200

In [3]:
#The .text method extracts the HTML content as a string in order to make it readable.
data  = requests.get(url).text
## print(data) Comenté esta instrucción porque ya se verificó que efectivamente se leyó la página

#### 2. Parse the html content

We will take the raw HTML content of a webpage or a string of HTML code which needs to be parsed and transformed into a structured, hierarchical format that can be more easily analyzed and manipulated in Python. This can be done using a Python library called Beautiful Soup.

In [4]:
#Create a soup object
sopaesta=BeautifulSoup(data, "html5lib")

In [5]:
#Leer todas las tablas HTML y guardarlas en un objeto pandas
table_list = pd.read_html(url, flavor='bs4')
# ¿Cuántas tablas hay?
len(table_list)

24

In [6]:
## De la página web solo vamos a usar las dos primeras tablas. La primera ha quedado guardada en en table_list en el índice 0
Positions=table_list[0]
Positions

,RL,Equipo,PJ,PG,PE,PP,GF,GC,DG,Pts,Pts/PJ,xG,xGA,xGD,xGD/90,Últimos 5,Asistencia,Máximo Goleador del Equipo,Portero,Notas
0,1,Tottenham,10,8,2,0,22,9,13,26,2.6,17.6,12.4,5.2,0.52,PE PG PG PG PG,61726,Son Heung-min - 8,Guglielmo Vicario,NaN
1,2,Arsenal,10,7,3,0,23,8,15,24,2.4,18.6,7.9,10.7,1.07,PE PG PG PE PG,60113,Eddie Nketiah - 5,David Raya,NaN
2,3,Manchester City,10,8,0,2,22,7,15,24,2.4,19.6,7.2,12.4,1.24,PG PP PP PG PG,39945,Erling Haaland - 11,Ederson,NaN
3,4,Liverpool,10,7,2,1,23,9,14,23,2.3,22.3,12.1,10.2,1.02,PG PP PE PG PG,50747,Mohamed Salah - 8,Alisson,NaN
4,5,Aston Villa,10,7,1,2,26,14,12,22,2.2,19.3,14.6,4.7,0.47,PG PG PE PG PG,41332,"Ollie Watkins, Douglas Luiz - 5",Emiliano Martínez,NaN
5,6,Newcastle Utd,10,5,2,3,26,11,15,17,1.7,21.9,10.2,11.6,1.16,PG PG PE PG PE,51993,Callum Wilson - 7,Nick Pope,NaN
6,7,Brighton,10,5,2,3,23,19,4,17,1.7,18.7,15.2,3.5,0.35,PG PP PE PP PE,31653,Evan Ferguson - 5,Jason Steele,NaN
7,8,Manchester Utd,10,5,0,5,11,16,-5,15,1.5,14.7,17.5,-2.8,-0.28,PG PP PG PG PP,61238,Scott McTominay - 3,André Onana,NaN
8,9,West Ham,10,4,2,4,16,17,-1,14,1.4,14.0,19.1,-5.1,-0.51,PP PG PE PP PP,49972,Jarrod Bowen - 6,Alphonse Areola,NaN
9,10,Brentford,10,3,4,3,16,12,4,13,1.3,19.0,12.8,6.2,0.62,PP PE PP PG PG,17009,Bryan Mbeumo - 6,Mark Flekken,NaN
10,11,Chelsea,10,3,3,4,13,11,2,12,1.2,18.2,11.3,6.9,0.69,PP PG PG PE PP,39801,Raheem Sterling - 3,Robert Sánchez,NaN
11,12,Wolves,10,3,3,4,13,17,-4,12,1.2,13.1,17.8,-4.7,-0.47,PE PG PE PG PE,31400,Hwang Hee-chan - 6,José Sá,NaN
12,13,Crystal Palace,10,3,3,4,8,13,-5,12,1.2,10.7,14.1,-3.4,-0.34,PE PG PE PP PP,19804,Odsonne Édouard - 4,Sam Johnstone,NaN
13,14,Fulham,10,3,3,4,9,16,-7,12,1.2,10.4,18.2,-7.8,-0.78,PE PP PG PP PE,24377,"Bobby Reid, João Palhinha - 2",Bernd Leno,NaN
14,15,Everton,10,3,1,6,10,14,-4,10,1.0,15.7,13.1,2.6,0.26,PG PP PG PP PG,39222,"Abdoulaye Doucouré, Dominic Calvert-Lewin - 3",Jordan Pickford,NaN
15,16,Nott'ham Forest,10,2,4,4,10,15,-5,10,1.0,11.2,15.7,-4.5,-0.45,PP PE PE PE PP,29189,"Chris Wood, Taiwo Awoniyi - 3",Matt Turner,NaN
16,17,Bournemouth,10,1,3,6,8,21,-13,6,0.6,10.5,21.8,-11.3,-1.13,PP PP PP PP PG,10959,Dominic Solanke - 4,Neto,NaN
17,18,Luton Town,10,1,2,7,9,20,-11,5,0.5,11.7,19.9,-8.3,-0.83,PG PP PP PE PP,10726,Carlton Morris - 3,Thomas Kaminski,NaN
18,19,Burnley,10,1,1,8,8,25,-17,4,0.4,8.5,18.9,-10.4,-1.04,PP PG PP PP PP,21632,Lyle Foster - 3,James Trafford,NaN
19,20,Sheffield Utd,10,0,1,9,7,29,-22,1,0.1,7.5,23.5,-15.9,-1.59,PP PP PP PP PP,31265,Gustavo Hamer - 2,Wes Foderingham,NaN

In [8]:
## Eliminando la column RL y Notas
Positions.drop(['RL','Notas'], axis=1, inplace=True)
Positions

,Equipo,PJ,PG,PE,PP,GF,GC,DG,Pts,Pts/PJ,xG,xGA,xGD,xGD/90,Últimos 5,Asistencia,Máximo Goleador del Equipo,Portero
0,Tottenham,10,8,2,0,22,9,13,26,2.6,17.6,12.4,5.2,0.52,PE PG PG PG PG,61726,Son Heung-min - 8,Guglielmo Vicario
1,Arsenal,10,7,3,0,23,8,15,24,2.4,18.6,7.9,10.7,1.07,PE PG PG PE PG,60113,Eddie Nketiah - 5,David Raya
2,Manchester City,10,8,0,2,22,7,15,24,2.4,19.6,7.2,12.4,1.24,PG PP PP PG PG,39945,Erling Haaland - 11,Ederson
3,Liverpool,10,7,2,1,23,9,14,23,2.3,22.3,12.1,10.2,1.02,PG PP PE PG PG,50747,Mohamed Salah - 8,Alisson
4,Aston Villa,10,7,1,2,26,14,12,22,2.2,19.3,14.6,4.7,0.47,PG PG PE PG PG,41332,"Ollie Watkins, Douglas Luiz - 5",Emiliano Martínez
5,Newcastle Utd,10,5,2,3,26,11,15,17,1.7,21.9,10.2,11.6,1.16,PG PG PE PG PE,51993,Callum Wilson - 7,Nick Pope
6,Brighton,10,5,2,3,23,19,4,17,1.7,18.7,15.2,3.5,0.35,PG PP PE PP PE,31653,Evan Ferguson - 5,Jason Steele
7,Manchester Utd,10,5,0,5,11,16,-5,15,1.5,14.7,17.5,-2.8,-0.28,PG PP PG PG PP,61238,Scott McTominay - 3,André Onana
8,West Ham,10,4,2,4,16,17,-1,14,1.4,14.0,19.1,-5.1,-0.51,PP PG PE PP PP,49972,Jarrod Bowen - 6,Alphonse Areola
9,Brentford,10,3,4,3,16,12,4,13,1.3,19.0,12.8,6.2,0.62,PP PE PP PG PG,17009,Bryan Mbeumo - 6,Mark Flekken
10,Chelsea,10,3,3,4,13,11,2,12,1.2,18.2,11.3,6.9,0.69,PP PG PG PE PP,39801,Raheem Sterling - 3,Robert Sánchez
11,Wolves,10,3,3,4,13,17,-4,12,1.2,13.1,17.8,-4.7,-0.47,PE PG PE PG PE,31400,Hwang Hee-chan - 6,José Sá
12,Crystal Palace,10,3,3,4,8,13,-5,12,1.2,10.7,14.1,-3.4,-0.34,PE PG PE PP PP,19804,Odsonne Édouard - 4,Sam Johnstone
13,Fulham,10,3,3,4,9,16,-7,12,1.2,10.4,18.2,-7.8,-0.78,PE PP PG PP PE,24377,"Bobby Reid, João Palhinha - 2",Bernd Leno
14,Everton,10,3,1,6,10,14,-4,10,1.0,15.7,13.1,2.6,0.26,PG PP PG PP PG,39222,"Abdoulaye Doucouré, Dominic Calvert-Lewin - 3",Jordan Pickford
15,Nott'ham Forest,10,2,4,4,10,15,-5,10,1.0,11.2,15.7,-4.5,-0.45,PP PE PE PE PP,29189,"Chris Wood, Taiwo Awoniyi - 3",Matt Turner
16,Bournemouth,10,1,3,6,8,21,-13,6,0.6,10.5,21.8,-11.3,-1.13,PP PP PP PP PG,10959,Dominic Solanke - 4,Neto
17,Luton Town,10,1,2,7,9,20,-11,5,0.5,11.7,19.9,-8.3,-0.83,PG PP PP PE PP,10726,Carlton Morris - 3,Thomas Kaminski
18,Burnley,10,1,1,8,8,25,-17,4,0.4,8.5,18.9,-10.4,-1.04,PP PG PP PP PP,21632,Lyle Foster - 3,James Trafford
19,Sheffield Utd,10,0,1,9,7,29,-22,1,0.1,7.5,23.5,-15.9,-1.59,PP PP PP PP PP,31265,Gustavo Hamer - 2,Wes Foderingham

<h4>Leyendo ahora la tabla 2 que quedó en el objeto table list </h4>

In [9]:
TeamStats = table_list[2]
TeamStats

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
               Equipo                 PL               Edad
0             Arsenal                 23               25.1
1         Aston Villa                 23               27.1
2         Bournemouth                 25               25.7
3           Brentford                 25               26.4
4            Brighton                 25               27.3
5             Burnley                 24               24.8
6             Chelsea                 23               25.0
7      Crystal Palace                 21               27.6
8             Everton                 23               27.3
9              Fulham                 23               29.4
10          Liverpool                 21               27.2
11         Luton Town                 22               27.1
12    Manchester City                 25               26.7
13     Manchester Utd                 25               27.3
14      Newcastle Utd                 21               28.1
15    Nott'ham Forest                 26               26.7
16      Sheffield Utd                 27               26.8
17          Tottenham                 23               25.3
18           West Ham                 20               28.9
19             Wolves                 21               26.9

   Unnamed: 3_level_0 Tiempo Jugado                    Rendimiento      ...  \
                 Pos.            PJ Titular  Mín  90 s        Gls. Ass  ...
0                60.7            10     110  900  10.0          22  12  ...
1                52.1            10     110  900  10.0          24  17  ...
2                43.2            10     110  900  10.0           8   5  ...
3                47.3            10     110  900  10.0          16  11  ...
4                59.7            10     110  900  10.0          22  17  ...
5                49.5            10     110  900  10.0           8   8  ...
6                61.8            10     110  900  10.0          12   7  ...
7                42.4            10     110  900  10.0           8   7  ...
8                42.6            10     110  900  10.0          10   6  ...
9                49.0            10     110  900  10.0           8   3  ...
10               57.0            10     110  900  10.0          21  13  ...
11               37.1            10     110  900  10.0           8   4  ...
12               63.0            10     110  900  10.0          22  16  ...
13               53.3            10     110  900  10.0          11   9  ...
14               54.3            10     110  900  10.0          26  16  ...
15               39.4            10     110  900  10.0          10   9  ...
16               38.0            10     110  900  10.0           5   2  ...
17               61.6            10     110  900  10.0          19  17  ...
18               40.9            10     110  900  10.0          16  14  ...
19               47.1            10     110  900  10.0          12  11  ...

   Por 90 Minutos
             Gls.  Ast  G+A G-TP G+A-TP    xG   xAG xG+xAG  npxG npxG+xAG
0             2.2  1.2  3.4  1.6    2.8  1.86  1.06   2.92  1.41     2.47
1             2.4  1.7  4.1  2.1    3.8  1.93  1.35   3.27  1.70     3.04
2             0.8  0.5  1.3  0.8    1.3  1.05  0.70   1.76  1.05     1.76
3             1.6  1.1  2.7  1.4    2.5  1.90  1.42   3.32  1.77     3.19
4             2.2  1.7  3.9  2.1    3.8  1.87  1.48   3.36  1.79     3.28
5             0.8  0.8  1.6  0.8    1.6  0.85  0.70   1.55  0.85     1.55
6             1.2  0.7  1.9  1.0    1.7  1.82  1.18   3.00  1.59     2.76
7             0.8  0.7  1.5  0.8    1.5  1.07  0.91   1.98  1.07     1.98
8             1.0  0.6  1.6  1.0    1.6  1.57  1.23   2.79  1.57     2.79
9             0.8  0.3  1.1  0.8    1.1  1.04  0.74   1.78  1.04     1.78
10            2.1  1.3  3.4  1.8    3.1  2.23  1.51   3.74  1.89     3.41
11            0.8  0.4  1.2  0.6    1.0  1.17  0.76   1.93  1.01     1.78
12            2.2  1.6  3.8  2.0    3.6  1.96  1.46   3.42  1.73     3.19
13            1.1  0.9  2.0  1.0    1.9  1.47  1.21   2.68  1.39     2.60
14            2.6  1.6  4.2  2.3    3.9  2.19  1.38   3.56  1.95     3.33
15            1.0  0.9  1.9  1.0    1.9  1.12  0.82   1.94  1.12     1.94
16            0.5  0.2  0.7  0.4    0.6  0.75  0.43   1.18  0.68     1.10
17            1.9  1.7  3.6  1.9    3.6  1.76  1.48   3.25  1.76     3.25
18            1.6  1.4  3.0  1.5    2.9  1.40  1.04   2.44  1.32     2.36
19            1.2  1.1  2.3  1.2    2.3  1.31  1.01   2.32  1.31     2.32

[20 rows x 32 columns]

#### Vemos que tenemos como varios niveles en los encabezados de las columnas, una vaina fea ahí. Eliminemos el nivel de mas arriba.

In [10]:
TeamStats.columns=TeamStats.columns.droplevel()
TeamStats

,Equipo,PL,Edad,Pos.,PJ,Titular,Mín,90 s,Gls.,Ass,...,Gls.,Ast,G+A,G-TP,G+A-TP,xG,xAG,xG+xAG,npxG,npxG+xAG
0,Arsenal,23,25.1,60.7,10,110,900,10.0,22,12,...,2.2,1.2,3.4,1.6,2.8,1.86,1.06,2.92,1.41,2.47
1,Aston Villa,23,27.1,52.1,10,110,900,10.0,24,17,...,2.4,1.7,4.1,2.1,3.8,1.93,1.35,3.27,1.70,3.04
2,Bournemouth,25,25.7,43.2,10,110,900,10.0,8,5,...,0.8,0.5,1.3,0.8,1.3,1.05,0.70,1.76,1.05,1.76
3,Brentford,25,26.4,47.3,10,110,900,10.0,16,11,...,1.6,1.1,2.7,1.4,2.5,1.90,1.42,3.32,1.77,3.19
4,Brighton,25,27.3,59.7,10,110,900,10.0,22,17,...,2.2,1.7,3.9,2.1,3.8,1.87,1.48,3.36,1.79,3.28
5,Burnley,24,24.8,49.5,10,110,900,10.0,8,8,...,0.8,0.8,1.6,0.8,1.6,0.85,0.70,1.55,0.85,1.55
6,Chelsea,23,25.0,61.8,10,110,900,10.0,12,7,...,1.2,0.7,1.9,1.0,1.7,1.82,1.18,3.00,1.59,2.76
7,Crystal Palace,21,27.6,42.4,10,110,900,10.0,8,7,...,0.8,0.7,1.5,0.8,1.5,1.07,0.91,1.98,1.07,1.98
8,Everton,23,27.3,42.6,10,110,900,10.0,10,6,...,1.0,0.6,1.6,1.0,1.6,1.57,1.23,2.79,1.57,2.79
9,Fulham,23,29.4,49.0,10,110,900,10.0,8,3,...,0.8,0.3,1.1,0.8,1.1,1.04,0.74,1.78,1.04,1.78
10,Liverpool,21,27.2,57.0,10,110,900,10.0,21,13,...,2.1,1.3,3.4,1.8,3.1,2.23,1.51,3.74,1.89,3.41
11,Luton Town,22,27.1,37.1,10,110,900,10.0,8,4,...,0.8,0.4,1.2,0.6,1.0,1.17,0.76,1.93,1.01,1.78
12,Manchester City,25,26.7,63.0,10,110,900,10.0,22,16,...,2.2,1.6,3.8,2.0,3.6,1.96,1.46,3.42,1.73,3.19
13,Manchester Utd,25,27.3,53.3,10,110,900,10.0,11,9,...,1.1,0.9,2.0,1.0,1.9,1.47,1.21,2.68,1.39,2.60
14,Newcastle Utd,21,28.1,54.3,10,110,900,10.0,26,16,...,2.6,1.6,4.2,2.3,3.9,2.19,1.38,3.56,1.95,3.33
15,Nott'ham Forest,26,26.7,39.4,10,110,900,10.0,10,9,...,1.0,0.9,1.9,1.0,1.9,1.12,0.82,1.94,1.12,1.94
16,Sheffield Utd,27,26.8,38.0,10,110,900,10.0,5,2,...,0.5,0.2,0.7,0.4,0.6,0.75,0.43,1.18,0.68,1.10
17,Tottenham,23,25.3,61.6,10,110,900,10.0,19,17,...,1.9,1.7,3.6,1.9,3.6,1.76,1.48,3.25,1.76,3.25
18,West Ham,20,28.9,40.9,10,110,900,10.0,16,14,...,1.6,1.4,3.0,1.5,2.9,1.40,1.04,2.44,1.32,2.36
19,Wolves,21,26.9,47.1,10,110,900,10.0,12,11,...,1.2,1.1,2.3,1.2,2.3,1.31,1.01,2.32,1.31,2.32

In [11]:
#Veamos los nombres de las columnas
print(TeamStats.columns)

Index(['Equipo', 'PL', 'Edad', 'Pos.', 'PJ', 'Titular', 'Mín', '90 s', 'Gls.',
       'Ass', 'G+A', 'G-TP', 'TP', 'TPint', 'TA', 'TR', 'xG', 'npxG', 'xAG',
       'npxG+xAG', 'PrgC', 'PrgP', 'Gls.', 'Ast', 'G+A', 'G-TP', 'G+A-TP',
       'xG', 'xAG', 'xG+xAG', 'npxG', 'npxG+xAG'],
      dtype='object')

In [12]:
##Eliminando unas columnas que no usaremos
TeamStats.drop(['PL','xG', 'npxG', 'xAG','npxG+xAG', 'PrgC', 'PrgP', 'Gls.', 'Ast', 'G+A', 'G-TP', 'G+A-TP','xG', 'xAG', 'xG+xAG', 'npxG', 'npxG+xAG'], axis=1, inplace=True)
TeamStats

,Equipo,Edad,Pos.,PJ,Titular,Mín,90 s,Ass,TP,TPint,TA,TR
0,Arsenal,25.1,60.7,10,110,900,10.0,12,6,6,17,1
1,Aston Villa,27.1,52.1,10,110,900,10.0,17,3,3,25,0
2,Bournemouth,25.7,43.2,10,110,900,10.0,5,0,0,17,1
3,Brentford,26.4,47.3,10,110,900,10.0,11,2,2,27,0
4,Brighton,27.3,59.7,10,110,900,10.0,17,1,1,25,0
5,Burnley,24.8,49.5,10,110,900,10.0,8,0,0,24,3
6,Chelsea,25.0,61.8,10,110,900,10.0,7,2,3,30,1
7,Crystal Palace,27.6,42.4,10,110,900,10.0,7,0,0,16,0
8,Everton,27.3,42.6,10,110,900,10.0,6,0,0,17,1
9,Fulham,29.4,49.0,10,110,900,10.0,3,0,0,25,2
10,Liverpool,27.2,57.0,10,110,900,10.0,13,3,4,20,4
11,Luton Town,27.1,37.1,10,110,900,10.0,4,2,2,17,0
12,Manchester City,26.7,63.0,10,110,900,10.0,16,2,3,20,2
13,Manchester Utd,27.3,53.3,10,110,900,10.0,9,1,1,24,0
14,Newcastle Utd,28.1,54.3,10,110,900,10.0,16,3,3,27,0
15,Nott'ham Forest,26.7,39.4,10,110,900,10.0,9,0,0,31,2
16,Sheffield Utd,26.8,38.0,10,110,900,10.0,2,1,1,31,1
17,Tottenham,25.3,61.6,10,110,900,10.0,17,0,0,32,1
18,West Ham,28.9,40.9,10,110,900,10.0,14,1,1,26,1
19,Wolves,26.9,47.1,10,110,900,10.0,11,0,0,34,3

In [13]:
##Ejecutando merge para fusionar los dos dataframes Position and TeamStats. Le decimos las columnas por las que queremos se una (las que se repiten)
GenStats=pd.merge(Positions, TeamStats, how ='left', on=['Equipo','PJ'])

#Ordenando el dataset por orden alfabético de acuerdo con la columna Equipo; inplace=True para que haga la ordenación en el mismo dataframe y no en una copia,
# y finalmente ignore_index=True para que descarte el cambio de orden que ocurrirá por cuenta de ejecutar 'sort_values' en la columna 'indices'  y asigne uno nuevo.
GenStats.sort_values('Equipo', inplace=True, ignore_index=True)

## Visualizar como quedó el dataframe 
GenStats

##Otra forma de unir los dos dataframes, solo qu esta dejará la columna usada para hacer la concatenación (en este caso Equipo) en un nivel y el resto de headers en otro
#pru=pd.concat([Positions.set_index('Equipo'),TeamStats.set_index('Equipo')], axis=1, join='outer')
#pru

,Equipo,PJ,PG,PE,PP,GF,GC,DG,Pts,Pts/PJ,...,Edad,Pos.,Titular,Mín,90 s,Ass,TP,TPint,TA,TR
0,Arsenal,10,7,3,0,23,8,15,24,2.4,...,25.1,60.7,110,900,10.0,12,6,6,17,1
1,Aston Villa,10,7,1,2,26,14,12,22,2.2,...,27.1,52.1,110,900,10.0,17,3,3,25,0
2,Bournemouth,10,1,3,6,8,21,-13,6,0.6,...,25.7,43.2,110,900,10.0,5,0,0,17,1
3,Brentford,10,3,4,3,16,12,4,13,1.3,...,26.4,47.3,110,900,10.0,11,2,2,27,0
4,Brighton,10,5,2,3,23,19,4,17,1.7,...,27.3,59.7,110,900,10.0,17,1,1,25,0
5,Burnley,10,1,1,8,8,25,-17,4,0.4,...,24.8,49.5,110,900,10.0,8,0,0,24,3
6,Chelsea,10,3,3,4,13,11,2,12,1.2,...,25.0,61.8,110,900,10.0,7,2,3,30,1
7,Crystal Palace,10,3,3,4,8,13,-5,12,1.2,...,27.6,42.4,110,900,10.0,7,0,0,16,0
8,Everton,10,3,1,6,10,14,-4,10,1.0,...,27.3,42.6,110,900,10.0,6,0,0,17,1
9,Fulham,10,3,3,4,9,16,-7,12,1.2,...,29.4,49.0,110,900,10.0,3,0,0,25,2
10,Liverpool,10,7,2,1,23,9,14,23,2.3,...,27.2,57.0,110,900,10.0,13,3,4,20,4
11,Luton Town,10,1,2,7,9,20,-11,5,0.5,...,27.1,37.1,110,900,10.0,4,2,2,17,0
12,Manchester City,10,8,0,2,22,7,15,24,2.4,...,26.7,63.0,110,900,10.0,16,2,3,20,2
13,Manchester Utd,10,5,0,5,11,16,-5,15,1.5,...,27.3,53.3,110,900,10.0,9,1,1,24,0
14,Newcastle Utd,10,5,2,3,26,11,15,17,1.7,...,28.1,54.3,110,900,10.0,16,3,3,27,0
15,Nott'ham Forest,10,2,4,4,10,15,-5,10,1.0,...,26.7,39.4,110,900,10.0,9,0,0,31,2
16,Sheffield Utd,10,0,1,9,7,29,-22,1,0.1,...,26.8,38.0,110,900,10.0,2,1,1,31,1
17,Tottenham,10,8,2,0,22,9,13,26,2.6,...,25.3,61.6,110,900,10.0,17,0,0,32,1
18,West Ham,10,4,2,4,16,17,-1,14,1.4,...,28.9,40.9,110,900,10.0,14,1,1,26,1
19,Wolves,10,3,3,4,13,17,-4,12,1.2,...,26.9,47.1,110,900,10.0,11,0,0,34,3

In [14]:
#Revisando el tipo de datos en cada columna
GenStats.dtypes

Equipo                         object
PJ                              int64
PG                              int64
PE                              int64
PP                              int64
GF                              int64
GC                              int64
DG                              int64
Pts                             int64
Pts/PJ                        float64
xG                            float64
xGA                           float64
xGD                           float64
xGD/90                        float64
Últimos 5                      object
Asistencia                      int64
Máximo Goleador del Equipo     object
Portero                        object
Edad                          float64
Pos.                          float64
Titular                         int64
Mín                             int64
90 s                          float64
Ass                             int64
TP                              int64
TPint                           int64
TA                              int64
TR                              int64
dtype: object

In [15]:
GenStats.columns

Index(['Equipo', 'PJ', 'PG', 'PE', 'PP', 'GF', 'GC', 'DG', 'Pts', 'Pts/PJ',
       'xG', 'xGA', 'xGD', 'xGD/90', 'Últimos 5', 'Asistencia',
       'Máximo Goleador del Equipo', 'Portero', 'Edad', 'Pos.', 'Titular',
       'Mín', '90 s', 'Ass', 'TP', 'TPint', 'TA', 'TR'],
      dtype='object')

In [16]:
# Traer el valor ubicado en la intersección entre fila= Chelsea columna = Asistencia, nada mas por ejercitar el uso del método loc
GenStats.loc[GenStats['Equipo']=='Chelsea', 'Asistencia']

6    39801
Name: Asistencia, dtype: int64

In [17]:
# Finalmente, el dataframe creado GenStats exportarlo a un archivo excel para después utilizarlo en otra aplicación.
#Este archivo excel quedará guardado en la misma carpeta donde esté guardado el archivo Pyhton actual que estamos trabajando
GenStats.to_excel('TeamStats.xlsx', index=False)

In [18]:
# lo mismo anterior pero guardarlo tipo csv
GenStats.to_csv('TeamStats.csv', index=False)